let movieList = [
    {
        title: 'Halloween',
        imageSource: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSh4s0ZI6Yh_zxjwhbNsatGFIuCrAuL5SGV5QDL_wrlZ0Uoeg7s',
        year: '1978',
        quantity: '3',
        price: '4.90'
    },
    {
        title: 'Scream',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQtWLu03bB5dBRlp70OYqeicYg9HXQ0yuaK3qZBnqACFxZ_SM5-',
        year: '1996',
        quantity: '1',
        price: '5.90',
    },
    {
        title: 'IT chapter 1',
        imageSource: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQeQ26eky-Cp_SXUJXxlgQTQEEc9esN9ctc7kXlaF8yzdvl2E3z',
        year: '2017',
        quantity: '0',
        price: '5.90',
    },
    {
        title: 'IT chapter 2',
        imageSource: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoR106dqgKciinSEguCJY38dTy_ZSu7Naspqwzsh0hnPrAQVdZ',
        year: '2019',
        quantity: '5',
        price: '3.90',
    },
    {
        title: 'Evil Dead',
        imageSource: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0UqPxR0nwPJn_icFW3odQMspUEHRZqIHWKo-d5rHSqMZ37Ga',
        year: '1981',
        quantity: '4',
        price: '6.90',
    },
    {
        title: 'The Hills Have Eyes',
        imageSource: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSmTRXJkZLiTXSNIPyU23lS3B4tEcET8fs7bMBwPSqn0D0Y2vVs',
        year: '1977',
        quantity: '3',
        price: '4.50',
    },
    {
        title: 'Paranormal Activity',
        imageSource: 'https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/paranormal-activity-2009/large_aylwfV996gmRst8TXyDvQUBvfMm.jpg',
        year: '2007',
        quantity: '2',
        price: '7.50',
    },
    {
        title: 'Insidious',
        imageSource: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHK_TzKZIMQ1yBuqhEUAS1jSQvuJ_dwOEZnp34_Mwwa_4xv2hG',
        year: '2010',
        quantity: '3',
        price: '4.50',
    },
    {
        title: 'The Exorcist',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqvU5RQ_ppeJUTwvuoRJZ3I4iBAEFW6vc7BlcQf7mc0qvh3Kue',
        year: '1973',
        quantity: '4',
        price: '6.90',
    },
    {
        title: 'The Thing',
        imageSource: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS8_TRLy8QuX-FGMlNnlM56gkpnk8wTzLGH4pYOufwK4ajSqFvv',
        year: '1982',
        quantity: '3',
        price: '4.50',
    },
    {
        title: 'Lost Boys',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSGAICfksn0ZVyxx2Do7CHyl-2Iwbqnqd3t7-zmjK0v-okI-uUF',
        year: '1987',
        quantity: '5',
        price: '3.90',
    },
    {
        title: 'Poltergeist',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQf_T60WLWpVuEDHyt19SAdIVhLPClinOiol5N12XSBTrjxspVx',
        year: '1982',
        quantity: '3',
        price: '4.50',
    },
    {
        title: 'The Conjouring',
        imageSource: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSPN0jFXkjp_5YGSBfMIWZb5VXfoECC9PFWmBci9gc4NhbUUa3m',
        year: '2013',
        quantity: '4',
        price: '7.50',
    },
    {
        title: 'The Texas Chainsaw Massacre',
        imageSource: 'https://www.movienewsletters.net/photos/039738R1.jpg',
        year: '1974',
        quantity: '6',
        price: '1.50',
    },
    {
        title: 'Candyman',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ08hoyqZEdtERnucK5LjnkhA0MHDptkfxOy6BoRpJh__a94HTp',
        year: '1992',
        quantity: '2',
        price: '7.50',
    },
    {
        title: 'The Last House on the Left',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQWnxgwD3hEppfX_DUWeRoMmxGf5cxivs5yxi1_ssFiOkKOL79R',
        year: '1972',
        quantity: '1',
        price: '7.50',
    },
    {
        title: 'Cell',
        imageSource: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ71rFhCeKYUOtshWqTtDRC6Sv7Tn6WP-7Uc4ovFiP6EpnXtrOR',
        year: '2016',
        quantity: '7',
        price: '2.50',
    },
    {
        title: 'Midsommar',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS7TC3aqR6kv9_4b9P6DZWqJPkuhPJAC26omhgaWvPlfkVqJbdj',
        year: '2019',
        quantity: '1',
        price: '10.50',
    },
    {
        title: 'Friday the 13th',
        imageSource: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR4R4QiXHTByVffq4IDxa0rNpQ9vu1MbNGdahWKjk9WXJTxYu9Z',
        year: '1980',
        quantity: '6',
        price: '5.40',
    },
    {
        title: 'A Nightmare on Elm Street',
        imageSource: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ2RTGj6wIs_FAWBC4KCXPuvdHRnt4anbzb9i_CHuU4yl6rM6EL',
        year: '1984',
        quantity: '4',
        price: '8.10',
    },
]
